# BRAND Dataset: Consumer Brand Familiarity and Liking (2020–2024)

**Author:** Valeria Ramírez Sánchez  
**Program:** Data Science and Mathematics Engineering, Tecnológico de Monterrey  
**Date:** October 29, 2026  
**Tools:** Google Colab, Python, pandas  
**Status:** Exploratory analysis in progress

## Research question

How did average brand familiarity and liking change from 2020 to 2024 for Netflix, Humana, Pfizer, M·A·C, and Boston Scientific?

## Data source

This project uses the BRAND (Brand Recognition and Attitude Norms Database), available through [ResearchBox](https://researchbox.org/1892). The dataset is licensed under CC BY 4.0.

Original study: Raffaelli et al., “BRAND: Brand recognition and attitude norms database,” *Behavior Research Methods*. [https://doi.org/10.3758/s13428-024-02525-x](https://doi.org/10.3758/s13428-024-02525-x)

## Scope and limitations

The data contains aggregated responses from U.S. residents. This notebook compares average familiarity and liking scores for five selected brands. The comparisons are descriptive: they do not establish why a score changed or show that the same people responded in both years.

## Notebook roadmap

1. Load and inspect the Excel workbook.
2. Understand the workbook structure and multi-row headers.
3. Prepare the analysis table and review missing values.
4. Compare brand familiarity and liking between 2020 and 2024.
5. Prepare and export a dataset for Power BI.
6. Summarize the findings and limitations.

## 1. Upload the workbook

The consolidated `BRAND_dataset.xlsx` workbook was downloaded from ResearchBox. This cell uploads it from the computer to the current Google Colab session so it can be inspected and analyzed.

In [18]:
from google.colab import files
uploaded = files.upload()

Saving BRAND_dataset.xlsx to BRAND_dataset (1).xlsx

## 2. Inspect the workbook and worksheet

The workbook structure is checked before loading the data. This helps identify which worksheet contains the dataset. The workbook has one worksheet, named `BRAND`.

In [19]:
#Nombres de las hojas del Excel
import pandas as pd
archivo = "BRAND_dataset.xlsx"
excel = pd.ExcelFile(archivo)
excel.sheet_names

['BRAND']

In [20]:
#Filas y coulmnas que contiene el dataset
df=pd.read_excel(archivo, sheet_name="BRAND")
print("Filas y columnas:", df.shape)
print("\nNombre de las columnas:")
print(df.columns.tolist())

display(df.head())

Filas y columnas: (599, 59)

Nombre de las columnas:
['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'BRAND 2020', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'BRAND 2024', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'REPORTS', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58']

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,BRAND 2020,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58
0,NaN,NaN,NaN,NaN,NaN,NaN,Brand Familiarity,NaN,NaN,Brand Liking,...,NaN,BrandZ,NaN,NaN,Interbrand,NaN,Forbes,NaN,NaN,Tenet
1,Brand Number,Brand Name,Category,Logo 2020,Logo 2024,NaN,n,M,SD,n,...,Brand Value 2023,Rank 2020,Brand Value 2020,Brand Contribution 2020,Rank 2020,Brand Value 2020,Rank 2020,Brand Value 2020,Brand Revenues,Rank 2020
2,1,Amazon,Tech,NaN,NaN,NaN,29,6.862069,0.350931,59,...,299280,1,334646,4,2,200667,4,135400,260500,8
3,2,Apple,Tech,NaN,NaN,NaN,30,6.733333,0.691492,58,...,297512,2,303381,4,1,322999,1,241200,260200,1
4,3,Google,Tech,NaN,NaN,NaN,30,6.833333,0.461133,58,...,281382,3,303217,4,4,165444,2,207500,145600,5

## 3. Inspect the table layout and headers

The worksheet uses three header rows: the data section, the measure, and the statistic or field name. Setting `header=None` prevents pandas from treating only the first row as the column names. The transposed preview makes it easier to inspect the headers and the first brand record. This step does not modify the data.

In [21]:
raw = pd.read_excel(archivo, sheet_name="BRAND", header=None)
display(raw.iloc[:4,:].T)

             0                  1                        2         3
0          NaN                NaN             Brand Number         1
1          NaN                NaN               Brand Name    Amazon
2          NaN                NaN                 Category      Tech
3          NaN                NaN                Logo 2020       NaN
4          NaN                NaN                Logo 2024       NaN
5          NaN                NaN                      NaN       NaN
6   BRAND 2020  Brand Familiarity                        n        29
7          NaN                NaN                        M  6.862069
8          NaN                NaN                       SD  0.350931
9          NaN       Brand Liking                        n        59
10         NaN                NaN                        M  5.508475
11         NaN                NaN                       SD  1.643932
12         NaN   Logo Familiarity                        n        31
13         NaN                NaN                        M  6.967742
14         NaN                NaN                       SD  0.179605
15         NaN        Logo Liking                        n        63
16         NaN                NaN                        M  5.714286
17         NaN                NaN                       SD  1.384576
18         NaN       Brand Memory                        n        60
19         NaN                NaN                     Hits       0.8
20         NaN                NaN                   Misses       0.2
21         NaN                NaN       Correct Rejections       0.8
22         NaN                NaN             False Alarms       0.2
23         NaN                NaN                     H-FA       0.6
24         NaN                NaN                       d'  1.683242
25         NaN                NaN           Criterion Bias      -0.0
26         NaN        Logo Memory                        n        59
27         NaN                NaN                     Hits      0.75
28         NaN                NaN                   Misses      0.25
29         NaN                NaN       Correct Rejections  0.888889
30         NaN                NaN             False Alarms  0.111111
31         NaN                NaN                     H-FA  0.638889
32         NaN                NaN                       d'   1.89513
33         NaN                NaN           Criterion Bias  0.273075
34  BRAND 2024  Brand Familiarity                        n        41
35         NaN                NaN                        M  6.756098
36         NaN                NaN                       SD  0.582258
37         NaN       Brand Liking                        n        41
38         NaN                NaN                        M  5.097561
39         NaN                NaN                       SD  2.130785
40         NaN   Logo Familiarity                        n        41
41         NaN                NaN                        M  6.682927
42         NaN                NaN                       SD  1.035351
43         NaN        Logo Liking                        n        41
44         NaN                NaN                        M  5.219512
45         NaN                NaN                       SD  1.541301
46     REPORTS     Brand Finance                 Rank 2019         1
47         NaN                NaN                Rank 2023         1
48         NaN                NaN         Brand Value 2019    187905
49         NaN                NaN         Brand Value 2023    299280
50         NaN             BrandZ                Rank 2020         1
51         NaN                NaN         Brand Value 2020    334646
52         NaN                NaN  Brand Contribution 2020         4
53         NaN         Interbrand                Rank 2020         2
54         NaN                NaN         Brand Value 2020    200667
55         NaN             Forbes               Rank 2020          4
56         NaN                NaN         Brand Value 2020    135400
57         NaN                NaN           Brand Revenues    260500
58         NaN              Tenet                Rank 2020         8

## 4. Display the headers in a readable format

The three header rows are displayed as a table with one row per original column. Forward filling carries section and measure labels across grouped columns, making the structure easier to understand. This creates a readable preview; it does not change the source data.

In [22]:
#Encabezados
encabezados = raw.iloc[:3,:].T.copy()
encabezados.columns =["Sección","Medida","Campo"]

encabezados["Sección"]=encabezados["Sección"].ffill()
encabezados["Medida"]=encabezados["Medida"].ffill()

display(encabezados)

       Sección             Medida                    Campo
0          NaN                NaN             Brand Number
1          NaN                NaN               Brand Name
2          NaN                NaN                 Category
3          NaN                NaN                Logo 2020
4          NaN                NaN                Logo 2024
5          NaN                NaN                      NaN
6   BRAND 2020  Brand Familiarity                        n
7   BRAND 2020  Brand Familiarity                        M
8   BRAND 2020  Brand Familiarity                       SD
9   BRAND 2020       Brand Liking                        n
10  BRAND 2020       Brand Liking                        M
11  BRAND 2020       Brand Liking                       SD
12  BRAND 2020   Logo Familiarity                        n
13  BRAND 2020   Logo Familiarity                        M
14  BRAND 2020   Logo Familiarity                       SD
15  BRAND 2020        Logo Liking                        n
16  BRAND 2020        Logo Liking                        M
17  BRAND 2020        Logo Liking                       SD
18  BRAND 2020       Brand Memory                        n
19  BRAND 2020       Brand Memory                     Hits
20  BRAND 2020       Brand Memory                   Misses
21  BRAND 2020       Brand Memory       Correct Rejections
22  BRAND 2020       Brand Memory             False Alarms
23  BRAND 2020       Brand Memory                     H-FA
24  BRAND 2020       Brand Memory                       d'
25  BRAND 2020       Brand Memory           Criterion Bias
26  BRAND 2020        Logo Memory                        n
27  BRAND 2020        Logo Memory                     Hits
28  BRAND 2020        Logo Memory                   Misses
29  BRAND 2020        Logo Memory       Correct Rejections
30  BRAND 2020        Logo Memory             False Alarms
31  BRAND 2020        Logo Memory                     H-FA
32  BRAND 2020        Logo Memory                       d'
33  BRAND 2020        Logo Memory           Criterion Bias
34  BRAND 2024  Brand Familiarity                        n
35  BRAND 2024  Brand Familiarity                        M
36  BRAND 2024  Brand Familiarity                       SD
37  BRAND 2024       Brand Liking                        n
38  BRAND 2024       Brand Liking                        M
39  BRAND 2024       Brand Liking                       SD
40  BRAND 2024   Logo Familiarity                        n
41  BRAND 2024   Logo Familiarity                        M
42  BRAND 2024   Logo Familiarity                       SD
43  BRAND 2024        Logo Liking                        n
44  BRAND 2024        Logo Liking                        M
45  BRAND 2024        Logo Liking                       SD
46     REPORTS     Brand Finance                 Rank 2019
47     REPORTS     Brand Finance                 Rank 2023
48     REPORTS     Brand Finance          Brand Value 2019
49     REPORTS     Brand Finance          Brand Value 2023
50     REPORTS             BrandZ                Rank 2020
51     REPORTS             BrandZ         Brand Value 2020
52     REPORTS             BrandZ  Brand Contribution 2020
53     REPORTS         Interbrand                Rank 2020
54     REPORTS         Interbrand         Brand Value 2020
55     REPORTS             Forbes               Rank 2020
56     REPORTS             Forbes         Brand Value 2020
57     REPORTS             Forbes           Brand Revenues
58     REPORTS              Tenet                Rank 2020

## 5. Prepare the analysis table

The first three rows contain the column headers, so they are combined into descriptive column names. The brand records begin after those header rows. The preparation removes only columns that are completely empty and rows without a brand name; partial missing values are kept for review.

The resulting table contains 597 brand records and 56 columns.

In [23]:
# Completar hacia la derecha los encabezados agrupados
nivel_1 = raw.iloc[0].ffill()
nivel_2 = raw.iloc[1].ffill()
nivel_3 = raw.iloc[2]

# Crear nombres de columnas combinando los tres niveles
nombres = []
for i in range(raw.shape[1]):
    partes = [
        str(x).strip()
        for x in [nivel_1.iloc[i], nivel_2.iloc[i], nivel_3.iloc[i]]
        if pd.notna(x) and str(x).strip() != ""
    ]
    nombres.append(" | ".join(partes))

# Los datos empiezan después de las tres filas de encabezados
data_limpia = raw.iloc[3:].copy().reset_index(drop=True)
data_limpia.columns = nombres

# Quitar solo columnas completamente vacías y filas sin nombre de marca
data_limpia = data_limpia.dropna(axis=1, how="all")
data_limpia = data_limpia.dropna(subset=["Brand Name"])

print("Dimensiones:", data_limpia.shape)

faltantes = pd.DataFrame({
    "faltantes": data_limpia.isna().sum(),
    "porcentaje": (data_limpia.isna().mean() * 100).round(1)
})

display(
    faltantes[faltantes["faltantes"] > 0]
    .sort_values("porcentaje", ascending=False)
)

display(data_limpia.head(3).iloc[:, :12])

Dimensiones: (597, 56)

                                                faltantes  porcentaje
REPORTS | Brand Finance | Brand Value 2023            498        83.4
BRAND 2020 | Brand Familiarity | M                     97        16.2
BRAND 2020 | Brand Familiarity | SD                    97        16.2
BRAND 2020 | Brand Liking | n                          97        16.2
BRAND 2020 | Brand Familiarity | n                     97        16.2
BRAND 2020 | Brand Liking | SD                         97        16.2
BRAND 2020 | Logo Familiarity | n                      97        16.2
BRAND 2020 | Logo Familiarity | M                      97        16.2
BRAND 2020 | Logo Familiarity | SD                     97        16.2
BRAND 2020 | Logo Liking | n                           97        16.2
BRAND 2020 | Logo Liking | M                           97        16.2
BRAND 2020 | Logo Liking | SD                          97        16.2
BRAND 2020 | Brand Memory | n                          97        16.2
BRAND 2020 | Brand Memory | Hits                       97        16.2
BRAND 2020 | Brand Memory | Misses                     97        16.2
BRAND 2020 | Brand Memory | Correct Rejections         97        16.2
BRAND 2020 | Brand Memory | False Alarms               97        16.2
BRAND 2020 | Brand Memory | H-FA                       97        16.2
BRAND 2020 | Brand Memory | d'                         97        16.2
BRAND 2020 | Brand Memory | Criterion Bias             97        16.2
BRAND 2020 | Brand Liking | M                          97        16.2
BRAND 2020 | Logo Memory | n                           97        16.2
BRAND 2020 | Logo Memory | Hits                        97        16.2
BRAND 2020 | Logo Memory | Correct Rejections          97        16.2
BRAND 2020 | Logo Memory | Misses                      97        16.2
BRAND 2020 | Logo Memory | H-FA                        97        16.2
BRAND 2020 | Logo Memory | d'                          97        16.2
BRAND 2020 | Logo Memory | Criterion Bias              97        16.2
BRAND 2020 | Logo Memory | False Alarms                97        16.2
REPORTS | BrandZ | Brand Value 2020                    97        16.2
REPORTS | BrandZ | Brand Contribution 2020             97        16.2
REPORTS | Interbrand | Rank 2020                       97        16.2
REPORTS | BrandZ | Rank 2020                           97        16.2
REPORTS | Brand Finance | Brand Value 2019             97        16.2
REPORTS | Brand Finance | Rank 2023                    97        16.2
REPORTS | Brand Finance | Rank 2019                    97        16.2
REPORTS | Forbes | Rank 2020                           97        16.2
REPORTS | Tenet | Rank 2020                            97        16.2
REPORTS | Forbes | Brand Value 2020                    97        16.2
REPORTS | Forbes | Brand Revenues                      97        16.2
REPORTS | Interbrand | Brand Value 2020                97        16.2
BRAND 2024 | Logo Familiarity | SD                      8         1.3
BRAND 2024 | Brand Liking | n                           8         1.3
BRAND 2024 | Brand Familiarity | SD                     8         1.3
BRAND 2024 | Brand Familiarity | M                      8         1.3
BRAND 2024 | Brand Familiarity | n                      8         1.3
BRAND 2024 | Logo Familiarity | M                       8         1.3
BRAND 2024 | Logo Familiarity | n                       8         1.3
BRAND 2024 | Brand Liking | SD                          8         1.3
BRAND 2024 | Brand Liking | M                           8         1.3
BRAND 2024 | Logo Liking | M                            8         1.3
BRAND 2024 | Logo Liking | SD                           8         1.3
BRAND 2024 | Logo Liking | n                            8         1.3

,Brand Number,Brand Name,Category,BRAND 2020 | Brand Familiarity | n,BRAND 2020 | Brand Familiarity | M,BRAND 2020 | Brand Familiarity | SD,BRAND 2020 | Brand Liking | n,BRAND 2020 | Brand Liking | M,BRAND 2020 | Brand Liking | SD,BRAND 2020 | Logo Familiarity | n,BRAND 2020 | Logo Familiarity | M,BRAND 2020 | Logo Familiarity | SD
0,1,Amazon,Tech,29,6.862069,0.350931,59,5.508475,1.643932,31,6.967742,0.179605
1,2,Apple,Tech,30,6.733333,0.691492,58,5.086207,1.949219,28,6.892857,0.31497
2,3,Google,Tech,30,6.833333,0.461133,58,5.655172,1.396132,28,6.964286,0.188982

## 6. Investigate missing data by year

This step identifies brands with no survey measures recorded for 2020 or 2024. These missing values appear to reflect which brands were included in each year's study, so they are not automatically errors. They should not be imputed or removed without considering the analysis.

In [24]:
columnas_2020 = [c for c in data_limpia.columns if c.startswith("BRAND 2020 |")]
columnas_2024 = [c for c in data_limpia.columns if c.startswith("BRAND 2024 |")]

sin_2020 = data_limpia[columnas_2020].isna().all(axis=1)
sin_2024 = data_limpia[columnas_2024].isna().all(axis=1)

print("Marcas sin medidas de 2020:", sin_2020.sum())
display(data_limpia.loc[sin_2020, ["Brand Name", "Category"]].head(15))

print("Marcas sin medidas de 2024:", sin_2024.sum())
display(data_limpia.loc[sin_2024, ["Brand Name", "Category"]])

Marcas sin medidas de 2020: 97

                Brand Name             Category
500                 Truist              Banking
501   Fidelity Investments              Banking
502               WhatsApp                Media
503              Evernorth           Healthcare
504                    AMD                 Tech
505                   MSCI  Commercial Services
506                   USPS            Logistics
507                    SLB            Oil & Gas
508            Chick-fil-A          Restaurants
509                  Marsh            Insurance
510  Wellcare Health Plans           Healthcare
511               Fortinet                 Tech
512                    PPG            Chemicals
513               DoorDash            Logistics
514                Winston              Tobacco

Marcas sin medidas de 2024: 8

           Brand Name             Category
112      Schlumberger            Oil & Gas
183             Kraft                 Food
192              BB&T              Banking
236     SunTrust Bank              Banking
248             Heinz                 Food
257           Twitter                 Tech
368  Waste Management            Utilities
381                L3  Aerospace & Defence

## 7. Select brands measured in both years

To compare 2020 and 2024, this step creates a separate table containing only brands with a familiarity score in both years. It includes 492 brands. The full `data_limpia` table remains unchanged, and Netflix is displayed as one example.

In [25]:
familiaridad_2020 = "BRAND 2020 | Brand Familiarity | M"
familiaridad_2024 = "BRAND 2024 | Brand Familiarity | M"

marcas_comparables = data_limpia.dropna(
    subset=[familiaridad_2020, familiaridad_2024]
).copy()

print("Marcas con familiaridad en ambos años:", len(marcas_comparables))

display(
    data_limpia.loc[
        data_limpia["Brand Name"].eq("Netflix"),
        ["Brand Name", "Category", familiaridad_2020, familiaridad_2024]
    ]
)

Marcas con familiaridad en ambos años: 492

,Brand Name,Category,BRAND 2020 | Brand Familiarity | M,BRAND 2024 | Brand Familiarity | M
39,Netflix,Tech,6.7,6.707317

## 8. Compare familiarity changes across brands

For each brand measured in both years, familiarity change is calculated as the 2024 mean minus the 2020 mean. Positive values indicate a higher average familiarity score in 2024; negative values indicate a lower score. The tables show the largest increases and decreases. These are descriptive comparisons and do not explain why the scores changed.

In [26]:
marcas_comparables["Cambio_familiaridad"] = (
    marcas_comparables[familiaridad_2024]
    - marcas_comparables[familiaridad_2020]
)

columnas_vista = [
    "Brand Name",
    "Category",
    familiaridad_2020,
    familiaridad_2024,
    "Cambio_familiaridad"
]

print("Mayores aumentos:")
display(
    marcas_comparables[columnas_vista]
    .sort_values("Cambio_familiaridad", ascending=False)
    .head(10)
)

print("Mayores disminuciones:")
display(
    marcas_comparables[columnas_vista]
    .sort_values("Cambio_familiaridad")
    .head(10)
)

Mayores aumentos:

,Brand Name,Category,BRAND 2020 | Brand Familiarity | M,BRAND 2024 | Brand Familiarity | M,Cambio_familiaridad
333,Grainger,Engineering & Construction,1.310345,3.641026,2.330681
367,Boston Scientific,Healthcare,1.290323,3.175,1.884677
168,Sherwin-Williams,Retail,3.586207,5.375,1.788793
172,Pfizer,Pharma,4.1,5.825,1.725
220,Wynn Resorts,Hotels,2.633333,4.205128,1.571795
80,Valero,Oil & Gas,2.566667,4.073171,1.506504
68,Humana,Healthcare,3.266667,4.692308,1.425641
90,Purina,Food,4.3,5.707317,1.407317
119,Nvidia,Tech,2.275862,3.658537,1.382675
311,Cintas,Commercial Services,1.933333,3.3,1.366667

Mayores disminuciones:

,Brand Name,Category,BRAND 2020 | Brand Familiarity | M,BRAND 2024 | Brand Familiarity | M,Cambio_familiaridad
247,M·A·C,Cosmetics & Personal Care,4.8,3.375,-1.425
278,Acuvue,Cosmetics & Personal Care,3.931034,2.9,-1.031034
102,Progressive,Insurance,6.103448,5.097561,-1.005887
321,Ulta Beauty,Retail,5.689655,4.825,-0.864655
352,Yoplait,Food,6.137931,5.275,-0.862931
186,The North Face,Apparel,5.8,5,-0.8
219,Maybelline,Cosmetics & Personal Care,5.612903,4.820513,-0.79239
255,TNT,Media,5.034483,4.292683,-0.7418
457,Olive Garden,Restaurants,6.333333,5.609756,-0.723577
350,Dick's Sporting Goods,Retail,6.1,5.4,-0.7

## 9. Inspect response counts and variability

This step displays the number of responses (`n`), average familiarity (`M`), and response variability (`SD`) for candidate brands in both years. These statistics add context to the changes in averages: they show how many responses contributed to each score and how spread out those responses were.

In [27]:
marcas_revisar = [
    "Boston Scientific", "Pfizer", "Humana",
    "Netflix", "M·A·C", "Progressive"
]

columnas = [
    "Brand Name",
    "Category",
    "BRAND 2020 | Brand Familiarity | n",
    "BRAND 2020 | Brand Familiarity | M",
    "BRAND 2020 | Brand Familiarity | SD",
    "BRAND 2024 | Brand Familiarity | n",
    "BRAND 2024 | Brand Familiarity | M",
    "BRAND 2024 | Brand Familiarity | SD",
    "Cambio_familiaridad"
]

display(
    marcas_comparables.loc[
        marcas_comparables["Brand Name"].isin(marcas_revisar),
        columnas
    ]
)

,Brand Name,Category,BRAND 2020 | Brand Familiarity | n,BRAND 2020 | Brand Familiarity | M,BRAND 2020 | Brand Familiarity | SD,BRAND 2024 | Brand Familiarity | n,BRAND 2024 | Brand Familiarity | M,BRAND 2024 | Brand Familiarity | SD,Cambio_familiaridad
39,Netflix,Tech,30,6.7,0.876907,41,6.707317,0.601826,0.007317
68,Humana,Healthcare,30,3.266667,2.148509,39,4.692308,1.764472,1.425641
102,Progressive,Insurance,29,6.103448,1.080503,41,5.097561,1.757909,-1.005887
172,Pfizer,Pharma,30,4.1,2.186952,40,5.825,1.034966,1.725
247,M·A·C,Cosmetics & Personal Care,30,4.8,2.426861,40,3.375,2.425162,-1.425
367,Boston Scientific,Healthcare,31,1.290323,0.82436,40,3.175,2.406055,1.884677

## 10. Compare brand liking across the selected brands

This table compares average brand liking for Netflix, Humana, Pfizer, M·A·C, and Boston Scientific in 2020 and 2024. It includes the number of responses (`n`), average score (`M`), and response variability (`SD`) for each year.

In [28]:
marcas_seleccionadas = [
    "Netflix",
    "Humana",
    "Pfizer",
    "M·A·C",
    "Boston Scientific"
]

columnas_gusto = [
    "Brand Name",
    "Category",
    "BRAND 2020 | Brand Liking | n",
    "BRAND 2020 | Brand Liking | M",
    "BRAND 2020 | Brand Liking | SD",
    "BRAND 2024 | Brand Liking | n",
    "BRAND 2024 | Brand Liking | M",
    "BRAND 2024 | Brand Liking | SD"
]

tabla_gusto = data_limpia.loc[
    data_limpia["Brand Name"].isin(marcas_seleccionadas),
    columnas_gusto
]

gusto_2020 = "BRAND 2020 | Brand Liking | M"
gusto_2024 = "BRAND 2024 | Brand Liking | M"

tabla_gusto = tabla_gusto.copy()
tabla_gusto["Cambio_gusto"] = (
    tabla_gusto[gusto_2024] - tabla_gusto[gusto_2020]
).round(3)

display(tabla_gusto)

,Brand Name,Category,BRAND 2020 | Brand Liking | n,BRAND 2020 | Brand Liking | M,BRAND 2020 | Brand Liking | SD,BRAND 2024 | Brand Liking | n,BRAND 2024 | Brand Liking | M,BRAND 2024 | Brand Liking | SD,Cambio_gusto
39,Netflix,Tech,58,6.172414,1.045255,41,5.682927,1.572244,-0.489487
68,Humana,Healthcare,58,4.103448,1.180093,39,3.923077,1.285232,-0.180371
172,Pfizer,Pharma,60,4.233333,1.477133,40,3.95,1.810935,-0.283333
247,M·A·C,Cosmetics & Personal Care,58,4.5,1.489731,40,4.5,1.339728,0.0
367,Boston Scientific,Healthcare,59,3.881356,1.099918,40,4.425,0.902631,0.543644

## 11. Prepare and export the Power BI dataset

This step selects the five brands and the familiarity and liking measures for 2020 and 2024. It calculates the change in each average score and exports the results as a XLSX file for Power BI.

In [32]:
marcas_seleccionadas = [
    "Netflix", "Humana", "Pfizer", "M·A·C", "Boston Scientific"
]

columnas = [
    "Brand Name",
    "Category",
    "BRAND 2020 | Brand Familiarity | n",
    "BRAND 2020 | Brand Familiarity | M",
    "BRAND 2020 | Brand Familiarity | SD",
    "BRAND 2024 | Brand Familiarity | n",
    "BRAND 2024 | Brand Familiarity | M",
    "BRAND 2024 | Brand Familiarity | SD",
    "BRAND 2020 | Brand Liking | n",
    "BRAND 2020 | Brand Liking | M",
    "BRAND 2020 | Brand Liking | SD",
    "BRAND 2024 | Brand Liking | n",
    "BRAND 2024 | Brand Liking | M",
    "BRAND 2024 | Brand Liking | SD"
]

powerbi_data = data_limpia.loc[
    data_limpia["Brand Name"].isin(marcas_seleccionadas),
    columnas
].copy()

powerbi_data = powerbi_data.rename(columns={
    "Brand Name": "Brand",
    "BRAND 2020 | Brand Familiarity | n": "Familiarity_n_2020",
    "BRAND 2020 | Brand Familiarity | M": "Familiarity_mean_2020",
    "BRAND 2020 | Brand Familiarity | SD": "Familiarity_SD_2020",
    "BRAND 2024 | Brand Familiarity | n": "Familiarity_n_2024",
    "BRAND 2024 | Brand Familiarity | M": "Familiarity_mean_2024",
    "BRAND 2024 | Brand Familiarity | SD": "Familiarity_SD_2024",
    "BRAND 2020 | Brand Liking | n": "Liking_n_2020",
    "BRAND 2020 | Brand Liking | M": "Liking_mean_2020",
    "BRAND 2020 | Brand Liking | SD": "Liking_SD_2020",
    "BRAND 2024 | Brand Liking | n": "Liking_n_2024",
    "BRAND 2024 | Brand Liking | M": "Liking_mean_2024",
    "BRAND 2024 | Brand Liking | SD": "Liking_SD_2024"
})

powerbi_data["Familiarity_change"] = (
    powerbi_data["Familiarity_mean_2024"]
    - powerbi_data["Familiarity_mean_2020"]
)

powerbi_data["Liking_change"] = (
    powerbi_data["Liking_mean_2024"]
    - powerbi_data["Liking_mean_2020"]
)

display(powerbi_data)

powerbi_data.to_excel(
    "brand_insights_powerbi.xlsx",
    index=False
)

from google.colab import files
files.download("brand_insights_powerbi.xlsx")

,Brand,Category,Familiarity_n_2020,Familiarity_mean_2020,Familiarity_SD_2020,Familiarity_n_2024,Familiarity_mean_2024,Familiarity_SD_2024,Liking_n_2020,Liking_mean_2020,Liking_SD_2020,Liking_n_2024,Liking_mean_2024,Liking_SD_2024,Familiarity_change,Liking_change
39,Netflix,Tech,30,6.7,0.876907,41,6.707317,0.601826,58,6.172414,1.045255,41,5.682927,1.572244,0.007317,-0.489487
68,Humana,Healthcare,30,3.266667,2.148509,39,4.692308,1.764472,58,4.103448,1.180093,39,3.923077,1.285232,1.425641,-0.180371
172,Pfizer,Pharma,30,4.1,2.186952,40,5.825,1.034966,60,4.233333,1.477133,40,3.95,1.810935,1.725,-0.283333
247,M·A·C,Cosmetics & Personal Care,30,4.8,2.426861,40,3.375,2.425162,58,4.5,1.489731,40,4.5,1.339728,-1.425,0.0
367,Boston Scientific,Healthcare,31,1.290323,0.82436,40,3.175,2.406055,59,3.881356,1.099918,40,4.425,0.902631,1.884677,0.543644

## 12. Summary and limitations

### Summary

Among the five selected brands, average familiarity increased the most for Boston Scientific (+1.88 points), followed by Pfizer (+1.73) and Humana (+1.43). M·A·C decreased (-1.43), while Netflix remained nearly unchanged (+0.01).

Average liking decreased for Netflix (-0.49), Pfizer (-0.28), and Humana (-0.18). M·A·C remained unchanged, while Boston Scientific increased (+0.54).

These are descriptive differences between average scores in 2020 and 2024. They do not establish why the scores changed.

### Limitations

- The survey responses came from U.S. residents, so the results should not be generalized to consumers in Mexico.
- This analysis includes five selected brands; it does not represent their entire industries.
- The number of responses varies by brand, measure, and year.
- The scores are aggregated by year and do not track the same individuals over time.